version: "3.8"
services:
  project:
    restart: always
    container_name: backend
    command: >
      /bin/sh -c "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - project